name: jobility_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Light.ttf
  assets:
    - assets/images/logo-big.png
    - assets/images/logo-medium.png
    - assets/images/logo-small.png
    - assets/images/light-logo.png
    - assets/images/cover.jpg
    - assets/images/registration-cover.jpg
    - assets/images/header.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/suitcase.png
    - assets/images/avatar.png