include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_const_constructors: ignore ignore ignore
    prefer_const_literals_to_create_immutables: ignore ignore
