// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAgCibG4esUksmgLI70AP7DoKetjBMSM',
    appId: '1:624311592722:web:727e65ad50e0734bda75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    authDomain: 'jobility-c1d00.firebaseapp.com',
    storageBucket: 'jobility-c1d00.appspot.com',
    measurementId: 'G-2S6K4HQ7WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzp5WddWm4YgPhsUrbSvF78n2PmR3OrDI',
    appId: '1:624311592722:android:de0b3f1a82fe3a88da75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    storageBucket: 'jobility-c1d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXRIwdME0HYwYJk7ZGQg6s8dz3-plP2Rk',
    appId: '1:624311592722:ios:734ca50263843e82da75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    storageBucket: 'jobility-c1d00.appspot.com',
    iosBundleId: 'com.example.jobilityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXRIwdME0HYwYJk7ZGQg6s8dz3-plP2Rk',
    appId: '1:624311592722:ios:734ca50263843e82da75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    storageBucket: 'jobility-c1d00.appspot.com',
    iosBundleId: 'com.example.jobilityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWAgCibG4esUksmgLI70AP7DoKetjBMSM',
    appId: '1:624311592722:web:9da7b9dadbc63c5eda75cb',
    messagingSenderId: '624311592722',
    projectId: 'jobility-c1d00',
    authDomain: 'jobility-c1d00.firebaseapp.com',
    storageBucket: 'jobility-c1d00.appspot.com',
    measurementId: 'G-1JTTL97EWG',
  );
}
